# docker compose -f docker-compose.yml -f docker-compose.nginx.yml up -d

services:
 nginx:
  build:
    context: .
    dockerfile: dockerfiles/nginx/Dockerfile
  container_name: nginx-docker
  ports:
    - 8080:80
  volumes:
    - static_volume:/app/staticfiles
  depends_on:
    - django-web
  restart: always

  django-web:
    ports:
      - []
    expose:
      - "8000"