services:
 db:
   image: postgres:17
   container_name: postgres-docker
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
     - "127.0.0.1:5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
 django-web:
   restart: always
   build:
    context: .
    dockerfile: dockerfiles/web/Dockerfile.prod
   container_name: django-docker
   expose:
     - "8000"
   volumes:
     - static_volume:/app/staticfiles
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DB_ENGINE}
     DATABASE_NAME: ${DB_NAME}
     DATABASE_USERNAME: ${DB_USER}
     DATABASE_PASSWORD: ${DB_PASSWORD}
     DATABASE_HOST: ${DB_HOST}
     DATABASE_PORT: ${DB_PORT}
   env_file:
     - .env

 nginx:
  build:
    context: .
    dockerfile: dockerfiles/nginx/Dockerfile
  container_name: nginx-docker
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./ssl:/etc/nginx/ssl:ro
    - static_volume:/app/staticfiles:ro
  depends_on:
    - django-web
  restart: always

volumes:
   postgres_data:
   static_volume: