# Generated by Django 5.1.7 on 2025-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.IntegerField(null=True),
        ),
    ]
