# Generated by Django 5.1.7 on 2025-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_workout_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
