# Generated by Django 5.1.12 on 2025-09-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workout', '0005_rename_name_typeworkout_name_workout_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneexercice',
            name='nb_repetition',
        ),
        migrations.RemoveField(
            model_name='oneexercice',
            name='nb_series',
        ),
        migrations.RemoveField(
            model_name='oneexercice',
            name='weight',
        ),
        migrations.AddField(
            model_name='exercice',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='oneexercice',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='oneexercice',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CardioExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercice')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrengthExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('nb_series', models.IntegerField()),
                ('nb_repetition', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercice')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
