# Generated by Django 5.1.12 on 2025-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_rename_name_workout_fr_typeworkout_name_workout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneexercice',
            options={'ordering': ['seance', 'position']},
        ),
        migrations.AddField(
            model_name='oneexercice',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
