# Generated by Django 5.1.12 on 2025-09-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_oneexercice_options_oneexercice_position'),
    ]

    operations = [
    ]
