# Generated by Django 5.1.13 on 2025-10-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0010_equipment_musclegroup_exercice_difficulty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("max_weight", "Max Weight"),
                            ("max_reps", "Max Reps"),
                            ("max_volume", "Max Volume"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField()),
                ("date_achieved", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_records",
                        to="workout.exercice",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_achieved"],
                "unique_together": {("exercise", "record_type")},
            },
        ),
    ]
