# Generated by Django 5.1.13 on 2025-10-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0011_personalrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalRecord",
        ),
    ]
