# Generated by Django 5.1.13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0012_delete_personalrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrengthSeriesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_number", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("weight", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strength_series_logs",
                        to="workout.exercice",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strength_series_logs",
                        to="workout.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["workout", "exercise", "series_number"],
            },
        ),
        migrations.CreateModel(
            name="CardioSeriesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_number", models.IntegerField()),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardio_series_logs",
                        to="workout.exercice",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardio_series_logs",
                        to="workout.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["workout", "exercise", "series_number"],
            },
        ),
    ]
