# Generated by Django 5.1.13

from django.db import migrations


def migrate_strength_to_series(apps, schema_editor):
    """Migrate StrengthExerciseLog to StrengthSeriesLog"""
    StrengthExerciseLog = apps.get_model("workout", "StrengthExerciseLog")
    StrengthSeriesLog = apps.get_model("workout", "StrengthSeriesLog")

    for old_log in StrengthExerciseLog.objects.all():
        # Create a series log for each series in the old log
        for series_num in range(1, old_log.nb_series + 1):
            StrengthSeriesLog.objects.create(
                exercise=old_log.exercise,
                workout=old_log.workout,
                series_number=series_num,
                reps=old_log.nb_repetition,
                weight=old_log.weight,
            )


def migrate_cardio_to_series(apps, schema_editor):
    """Migrate CardioExerciseLog to CardioSeriesLog"""
    CardioExerciseLog = apps.get_model("workout", "CardioExerciseLog")
    CardioSeriesLog = apps.get_model("workout", "CardioSeriesLog")

    for old_log in CardioExerciseLog.objects.all():
        # Create a single series log for each cardio exercise
        CardioSeriesLog.objects.create(
            exercise=old_log.exercise,
            workout=old_log.workout,
            series_number=1,
            duration_seconds=old_log.duration_seconds,
            distance_m=old_log.distance_m,
        )


def reverse_migrate(apps, schema_editor):
    """Reverse migration - delete series logs (data loss)"""
    StrengthSeriesLog = apps.get_model("workout", "StrengthSeriesLog")
    CardioSeriesLog = apps.get_model("workout", "CardioSeriesLog")
    StrengthSeriesLog.objects.all().delete()
    CardioSeriesLog.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0013_add_series_logs"),
    ]

    operations = [
        migrations.RunPython(
            migrate_strength_to_series,
            reverse_migrate,
        ),
        migrations.RunPython(
            migrate_cardio_to_series,
            reverse_migrate,
        ),
    ]
