# Generated by Django 5.1.15 on 2026-01-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0014_migrate_to_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.exercice",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="TemplateCardioSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_number", models.IntegerField()),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                (
                    "template_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.templateexercise",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Template Cardio Series",
                "ordering": ["template_exercise__position", "series_number"],
            },
        ),
        migrations.CreateModel(
            name="TemplateStrengthSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_number", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("weight", models.IntegerField()),
                (
                    "template_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.templateexercise",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Template Strength Series",
                "ordering": ["template_exercise__position", "series_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type_workout",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workout.typeworkout",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="templateexercise",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workout.workouttemplate",
            ),
        ),
    ]
