# Generated by Django 5.1.15 on 2026-02-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0015_templateexercise_templatecardioseries_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strengthexerciselog",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="strengthexerciselog",
            name="workout",
        ),
        migrations.AlterModelOptions(
            name="exercice",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="typeworkout",
            options={"ordering": ["name_workout"]},
        ),
        migrations.DeleteModel(
            name="CardioExerciseLog",
        ),
        migrations.DeleteModel(
            name="StrengthExerciseLog",
        ),
    ]
