# Generated by Django 5.1.15 on 2026-02-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0016_remove_strengthexerciselog_exercise_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oneexercice",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="oneexercice",
            name="object_id",
        ),
    ]
