# Generated by Django 5.1.8 on 2025-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_article_author_article_image_url_article_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFetchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_text', models.TextField(blank=True)),
                ('total_feeds', models.PositiveIntegerField(default=0)),
                ('processed_feeds', models.PositiveIntegerField(default=0)),
                ('articles_created', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
