# Generated by Django 5.1.4 on 2025-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projet_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='projet',
            name='description_fr',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='title_fr',
            field=models.CharField(default='titre', max_length=50),
            preserve_default=False,
        ),
    ]
