# Generated by Django 5.1.4 on 2025-02-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_exercice_typeworkout_workout_oneexercice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercice",
            old_name="name_en",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="exercice",
            name="name_fr",
        ),
    ]
