# Generated by Django 5.1.4 on 2025-03-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_oneexercice_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneexercice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='oneexercice',
            name='seance',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type_workout',
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
        migrations.DeleteModel(
            name='OneExercice',
        ),
        migrations.DeleteModel(
            name='TypeWorkout',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
