# Generated by Django 5.1.15 on 2026-02-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_remove_oneexercice_name_remove_oneexercice_seance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
