# Generated by Django 5.1.4 on 2025-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_oneexercice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneexercice',
            name='time',
            field=models.DurationField(default=0),
        ),
    ]
