# Generated by Django 5.1.4 on 2025-02-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_oneexercice_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneexercice',
            name='time',
        ),
    ]
