name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd portfolio/
            git pull origin main
            yes yes | .venv/bin/python manage.py collectstatic
            sudo systemctl restart nginx
            docker compose down
            docker compose -f docker-compose.prod.yml up --build -d
            docker system prune -f
 